"""
Canonical frontier model catalog — single source of truth for GET /api/v1/models.
Contributor guide: docs/REGISTRY.md
"""

from typing import Any, Dict, List

# Provider display metadata (models listed separately)
PROVIDER_META: Dict[str, Dict[str, Any]] = {
    "openai": {
        "label": "OpenAI",
        "description": "GPT-5.5 frontier family",
        "relayLabel": None,
    },
    "google": {
        "label": "Google",
        "description": "Gemini 3.5 & 3.1 models",
        "relayLabel": None,
    },
    "anthropic": {
        "label": "Anthropic",
        "description": "Claude Opus 4.8 & Sonnet 4.6",
        "relayLabel": "OpenRouter",
    },
    "opencode-go": {
        "label": "OpenCode Go",
        "description": "Curated models through OpenCode Go",
        "relayLabel": None,
    },
    "opencode-zen": {
        "label": "OpenCode Zen",
        "description": "Multi-protocol models through OpenCode Zen",
        "relayLabel": None,
    },
    "meta": {
        "label": "OpenRouter",
        "description": "Frontier OSS & relay endpoints",
        "relayLabel": "OpenRouter",
    },
    "custom": {
        "label": "Custom HTTP",
        "description": "OpenAI-compatible endpoint",
        "relayLabel": None,
    },
}

FRONTIER_CATALOG: List[Dict[str, Any]] = [
    # —— OpenAI (frontier) ——
    {
        "id": "gpt-5.5",
        "name": "GPT-5.5",
        "provider": "openai",
        "supportsStreaming": True,
        "contextWindow": "1M",
        "multimodal": True,
        "reasoning": True,
        "freeTier": False,
        "openSource": False,
        "relaySupported": True,
        "openRouterId": "openai/gpt-5.5",
        "typicalLatency": "~2.2s",
        "supportsWebSearch": False,
    },
    {
        "id": "gpt-5.5-pro",
        "name": "GPT-5.5 Pro",
        "provider": "openai",
        "supportsStreaming": True,
        "contextWindow": "1M",
        "multimodal": True,
        "reasoning": True,
        "freeTier": False,
        "openSource": False,
        "relaySupported": True,
        "openRouterId": "openai/gpt-5.5-pro",
        "typicalLatency": "~3.5s",
        "supportsWebSearch": False,
    },
    {
        "id": "gpt-5-mini",
        "name": "GPT-5 Mini",
        "provider": "openai",
        "supportsStreaming": True,
        "contextWindow": "400K",
        "multimodal": True,
        "reasoning": True,
        "freeTier": False,
        "openSource": False,
        "relaySupported": True,
        "openRouterId": "openai/gpt-5-mini",
        "typicalLatency": "~1.0s",
        "supportsWebSearch": False,
    },
    # —— Google (frontier) ——
    {
        "id": "gemini-3.1-pro-preview",
        "name": "Gemini 3.1 Pro",
        "provider": "google",
        "supportsStreaming": True,
        "contextWindow": "1M",
        "multimodal": True,
        "reasoning": True,
        "freeTier": False,
        "openSource": False,
        "relaySupported": True,
        "openRouterId": "google/gemini-3.1-pro-preview",
        "typicalLatency": "~2.4s",
    },
    {
        "id": "gemini-3.5-flash",
        "name": "Gemini 3.5 Flash",
        "provider": "google",
        "supportsStreaming": True,
        "contextWindow": "1M",
        "multimodal": True,
        "reasoning": True,
        "freeTier": False,
        "openSource": False,
        "relaySupported": True,
        "openRouterId": "google/gemini-3.5-flash",
        "typicalLatency": "~0.8s",
    },
    # —— Anthropic (frontier) ——
    {
        "id": "claude-opus-4-8",
        "name": "Claude Opus 4.8",
        "provider": "anthropic",
        "supportsStreaming": True,
        "contextWindow": "1M",
        "multimodal": True,
        "reasoning": True,
        "freeTier": False,
        "openSource": False,
        "relaySupported": True,
        "openRouterId": "anthropic/claude-opus-4.8",
        "typicalLatency": "~3.0s",
    },
    {
        "id": "claude-sonnet-4-6",
        "name": "Claude Sonnet 4.6",
        "provider": "anthropic",
        "supportsStreaming": True,
        "contextWindow": "1M",
        "multimodal": True,
        "reasoning": True,
        "freeTier": False,
        "openSource": False,
        "relaySupported": True,
        "openRouterId": "anthropic/claude-sonnet-4.6",
        "typicalLatency": "~2.0s",
    },
    # —— OpenCode Go ——
    {
        "id": "grok-4.5",
        "name": "Grok 4.5",
        "provider": "opencode-go",
        "supportsStreaming": True,
        "contextWindow": "—",
        "multimodal": False,
        "reasoning": False,
        "freeTier": False,
        "openSource": False,
        "relaySupported": False,
        "typicalLatency": "~2.0s",
        "supportsWebSearch": False,
        "source": "opencode",
    },
    {
        "id": "glm-5.2",
        "name": "GLM 5.2",
        "provider": "opencode-go",
        "supportsStreaming": True,
        "contextWindow": "—",
        "multimodal": False,
        "reasoning": False,
        "freeTier": False,
        "openSource": False,
        "relaySupported": False,
        "typicalLatency": "~2.0s",
        "supportsWebSearch": False,
        "source": "opencode",
    },
    {
        "id": "minimax-m3",
        "name": "MiniMax M3",
        "provider": "opencode-go",
        "supportsStreaming": True,
        "contextWindow": "—",
        "multimodal": False,
        "reasoning": False,
        "freeTier": False,
        "openSource": False,
        "relaySupported": False,
        "typicalLatency": "~2.0s",
        "supportsWebSearch": False,
        "source": "opencode",
    },
    {
        "id": "qwen3.7-plus",
        "name": "Qwen 3.7 Plus",
        "provider": "opencode-go",
        "supportsStreaming": True,
        "contextWindow": "—",
        "multimodal": False,
        "reasoning": False,
        "freeTier": False,
        "openSource": False,
        "relaySupported": False,
        "typicalLatency": "~2.0s",
        "supportsWebSearch": False,
        "source": "opencode",
    },
    # —— OpenCode Zen ——
    {
        "id": "gpt-5.6-sol",
        "name": "GPT 5.6 Sol",
        "provider": "opencode-zen",
        "supportsStreaming": True,
        "contextWindow": "—",
        "multimodal": False,
        "reasoning": False,
        "freeTier": False,
        "openSource": False,
        "relaySupported": False,
        "typicalLatency": "~2.0s",
        "supportsWebSearch": False,
        "source": "opencode",
    },
    {
        "id": "claude-sonnet-5",
        "name": "Claude Sonnet 5",
        "provider": "opencode-zen",
        "supportsStreaming": True,
        "contextWindow": "—",
        "multimodal": False,
        "reasoning": False,
        "freeTier": False,
        "openSource": False,
        "relaySupported": False,
        "typicalLatency": "~2.0s",
        "supportsWebSearch": False,
        "source": "opencode",
    },
    {
        "id": "gemini-3.6-flash",
        "name": "Gemini 3.6 Flash",
        "provider": "opencode-zen",
        "supportsStreaming": True,
        "contextWindow": "—",
        "multimodal": False,
        "reasoning": False,
        "freeTier": False,
        "openSource": False,
        "relaySupported": False,
        "typicalLatency": "~2.0s",
        "supportsWebSearch": False,
        "source": "opencode",
    },
    {
        "id": "deepseek-v4-flash-free",
        "name": "DeepSeek V4 Flash Free",
        "provider": "opencode-zen",
        "supportsStreaming": True,
        "contextWindow": "—",
        "multimodal": False,
        "reasoning": False,
        "freeTier": True,
        "openSource": False,
        "relaySupported": False,
        "typicalLatency": "~2.0s",
        "supportsWebSearch": False,
        "source": "opencode",
    },
    # —— OpenRouter / OSS relay ——
    {
        "id": "deepseek/deepseek-v4-flash",
        "name": "DeepSeek V4 Flash",
        "provider": "meta",
        "supportsStreaming": True,
        "contextWindow": "1M",
        "multimodal": False,
        "reasoning": True,
        "freeTier": False,
        "openSource": True,
        "relaySupported": True,
        "openRouterId": "deepseek/deepseek-v4-flash",
        "typicalLatency": "~1.4s",
    },
    {
        "id": "meta-llama/llama-4-maverick",
        "name": "Llama 4 Maverick",
        "provider": "meta",
        "supportsStreaming": True,
        "contextWindow": "128K",
        "multimodal": True,
        "reasoning": False,
        "freeTier": False,
        "openSource": True,
        "relaySupported": True,
        "openRouterId": "meta-llama/llama-4-maverick",
        "typicalLatency": "~1.8s",
    },
    {
        "id": "meta-llama/llama-4-scout",
        "name": "Llama 4 Scout",
        "provider": "meta",
        "supportsStreaming": True,
        "contextWindow": "128K",
        "multimodal": False,
        "reasoning": False,
        "freeTier": False,
        "openSource": True,
        "relaySupported": True,
        "openRouterId": "meta-llama/llama-4-scout",
        "typicalLatency": "~1.6s",
    },
    {
        "id": "qwen/qwen3-235b-a22b",
        "name": "Qwen 3",
        "provider": "meta",
        "supportsStreaming": True,
        "contextWindow": "128K",
        "multimodal": False,
        "reasoning": True,
        "freeTier": False,
        "openSource": True,
        "relaySupported": True,
        "openRouterId": "qwen/qwen3-235b-a22b",
        "typicalLatency": "~2.2s",
    },
    {
        "id": "google/gemma-3-27b-it",
        "name": "Gemma 3 27B",
        "provider": "meta",
        "supportsStreaming": True,
        "contextWindow": "128K",
        "multimodal": False,
        "reasoning": False,
        "freeTier": True,
        "openSource": True,
        "relaySupported": True,
        "openRouterId": "google/gemma-3-27b-it",
        "typicalLatency": "~1.2s",
    },
    {
        "id": "custom",
        "name": "Custom Model",
        "provider": "custom",
        "supportsStreaming": True,
        "contextWindow": "—",
        "multimodal": False,
        "reasoning": False,
        "freeTier": False,
        "openSource": False,
        "relaySupported": False,
        "typicalLatency": "~2.0s",
    },
]
