import type { ApiKeys } from "@/lib/secure-api-keys";
import type { SettingsSectionId } from "./settings-sections";

export type SettingsHandlersProps = {
  apiKeys: ApiKeys;
  setApiKeys: (keys: ApiKeys) => void;
  showKeys: Record<string, boolean>;
  toggleKeyVisibility: (keyName: string) => void;
  handleKeyChange: (keyName: string, value: string) => void;
  handleMetaRelayChange: (provider: "openrouter" | "together") => void;
  handleCustomConfigChange: (field: "baseUrl" | "keyHeader", value: string) => void;
  handleClear: () => void;
  hasValidKeys: boolean;
  openaiValid: boolean;
  googleValid: boolean;
  anthropicValid: boolean;
  opencodeValid: boolean;
  metaValid: boolean;
  customValid: boolean;
  password: string;
  setPassword: (v: string) => void;
  confirmPassword: string;
  setConfirmPassword: (v: string) => void;
  showExportDialog: boolean;
  setShowExportDialog: (v: boolean) => void;
  showImportDialog: boolean;
  setShowImportDialog: (v: boolean) => void;
  showSaveDialog: boolean;
  setShowSaveDialog: (v: boolean) => void;
  showLoadDialog: boolean;
  setShowLoadDialog: (v: boolean) => void;
  handleExport: () => void;
  handleImport: (file: File) => void;
  handleSaveToIndexedDB: () => void;
  handleLoadFromIndexedDB: () => void;
  handleDeleteFromIndexedDB: () => void;
  activeSection: SettingsSectionId;
  setActiveSection: (id: SettingsSectionId) => void;
};
