import type { ModelRegistryResponse } from "@/types/registry";

/** Embedded frontier catalog — used when backend is offline or running an old build. */
export const BUNDLED_FRONTIER_RESPONSE: ModelRegistryResponse = {
  version: "2",
  updatedAt: null,
  streaming: true,
  byok: true,
  openRouterHydrated: false,
  liveSync: false,
  fingerprint: "bundled-frontier",
  degraded: true,
  providers: [
    {
      id: "openai",
      label: "OpenAI",
      description: "GPT-5.5 frontier family",
      relayLabel: null,
      models: [
        {
          id: "gpt-5.5",
          name: "GPT-5.5",
          provider: "openai",
          supportsStreaming: true,
          contextWindow: "1M",
          multimodal: true,
          reasoning: true,
          freeTier: false,
          openSource: false,
          relaySupported: true,
        },
        {
          id: "gpt-5.5-pro",
          name: "GPT-5.5 Pro",
          provider: "openai",
          supportsStreaming: true,
          contextWindow: "1M",
          multimodal: true,
          reasoning: true,
          freeTier: false,
          openSource: false,
          relaySupported: true,
        },
        {
          id: "gpt-5-mini",
          name: "GPT-5 Mini",
          provider: "openai",
          supportsStreaming: true,
          contextWindow: "400K",
          multimodal: true,
          reasoning: true,
          freeTier: false,
          openSource: false,
          relaySupported: true,
        },
      ],
    },
    {
      id: "google",
      label: "Google",
      description: "Gemini 3.5 & 3.1",
      relayLabel: null,
      models: [
        {
          id: "gemini-3.1-pro-preview",
          name: "Gemini 3.1 Pro",
          provider: "google",
          supportsStreaming: true,
          contextWindow: "1M",
          multimodal: true,
          reasoning: true,
          freeTier: false,
          openSource: false,
          relaySupported: true,
        },
        {
          id: "gemini-3.5-flash",
          name: "Gemini 3.5 Flash",
          provider: "google",
          supportsStreaming: true,
          contextWindow: "1M",
          multimodal: true,
          reasoning: true,
          freeTier: false,
          openSource: false,
          relaySupported: true,
        },
      ],
    },
    {
      id: "anthropic",
      label: "Anthropic",
      description: "Claude Opus 4.8 & Sonnet 4.6",
      relayLabel: "OpenRouter",
      models: [
        {
          id: "claude-opus-4-8",
          name: "Claude Opus 4.8",
          provider: "anthropic",
          supportsStreaming: true,
          contextWindow: "1M",
          multimodal: true,
          reasoning: true,
          freeTier: false,
          openSource: false,
          relaySupported: true,
        },
        {
          id: "claude-sonnet-4-6",
          name: "Claude Sonnet 4.6",
          provider: "anthropic",
          supportsStreaming: true,
          contextWindow: "1M",
          multimodal: true,
          reasoning: true,
          freeTier: false,
          openSource: false,
          relaySupported: true,
        },
      ],
    },
    {
      id: "meta",
      label: "OpenRouter",
      description: "OSS & relay",
      relayLabel: "OpenRouter",
      models: [
        {
          id: "deepseek/deepseek-v4-flash",
          name: "DeepSeek V4 Flash",
          provider: "meta",
          supportsStreaming: true,
          contextWindow: "1M",
          multimodal: false,
          reasoning: true,
          freeTier: false,
          openSource: true,
          relaySupported: true,
        },
        {
          id: "meta-llama/llama-4-maverick",
          name: "Llama 4 Maverick",
          provider: "meta",
          supportsStreaming: true,
          contextWindow: "128K",
          multimodal: true,
          reasoning: false,
          freeTier: false,
          openSource: true,
          relaySupported: true,
        },
        {
          id: "meta-llama/llama-4-scout",
          name: "Llama 4 Scout",
          provider: "meta",
          supportsStreaming: true,
          contextWindow: "128K",
          multimodal: false,
          reasoning: false,
          freeTier: false,
          openSource: true,
          relaySupported: true,
        },
        {
          id: "qwen/qwen3-235b-a22b",
          name: "Qwen 3",
          provider: "meta",
          supportsStreaming: true,
          contextWindow: "128K",
          multimodal: false,
          reasoning: true,
          freeTier: false,
          openSource: true,
          relaySupported: true,
        },
      ],
    },
  ],
};

export function isLegacyApiRegistry(data: ModelRegistryResponse): boolean {
  const ids = new Set(
    (data.providers ?? []).flatMap((p) => (p.models ?? []).map((m) => m.id.toLowerCase()))
  );
  if (data.version === "1") return true;
  if (ids.has("gpt-4o") && !ids.has("gpt-5.5")) return true;
  if (ids.has("gemini-2.5-pro") && !ids.has("gemini-3.1-pro-preview")) return true;
  if (ids.has("claude-sonnet-4-20250514") && !ids.has("claude-sonnet-4-6")) return true;
  return false;
}
